# Generated by Django 5.0.2 on 2024-03-18 19:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leaderboard", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyleaderboard",
            name="date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="player",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
